name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git merge main --no-edit
          npm ci
          npm run build
          git add -f docs/*
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push origin gh-pages
